function lightReading = LRCread_lightReading(fileID)
%LRCREAD_LIGHTREADING Replace with native C functions
%   For use with MATLAB only. DO NOT use for codegen.

formatSpec = '%f %f %f %f %f %f %f';
C = textscan(fileID,formatSpec,...
    'Delimiter',',','HeaderLines',1,'TreatAsEmpty','null');
frewind(fileID);

lightReading = struct(      ...
    'timeUTC',      C(1),	...
    'timeOffset',	C(2),	...
    'red',          C(3),	...
    'green',        C(4),	...
    'blue',         C(5),	...
    'cla',          C(6),	...
    'cs',           C(7)	...
    );

end

