function activityReading = LRCread_activityReading(fileID)
%LRCREAD_ACTIVITYREADING Replace with native C functions
%   For use with MATLAB only. DO NOT use for codegen.

[timeUTC,timeOffset,activityIndex,activityCount] = importfile(fileID);

activityReading = struct(                       ...
    'timeUTC',          int32(timeUTC),         ...
    'timeOffset',       single(timeOffset),     ...
    'activityIndex',	double(activityIndex),	...
    'activityCount',	int32(activityCount)	...
    );

end


function [timeUTC,timeOffset,activityIndex,activityCount] = importfile(fileID)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIMEUTC,TIMEOFFSET,ACTIVITYINDEX,ACTIVITYCOUNT] = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   [TIMEUTC,TIMEOFFSET,ACTIVITYINDEX,ACTIVITYCOUNT] = IMPORTFILE(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [timeUTC,timeOffset,activityIndex,activityCount] =
%   importfile('activityReading.csv',2, 2);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/05/28 16:53:37

%% Initialize variables.
delimiter = ',';
startRow = 2;
endRow = inf;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
timeUTC = dataArray{:, 1};
timeOffset = dataArray{:, 2};
activityIndex = dataArray{:, 3};
activityCount = dataArray{:, 4};


end